import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type RouteContext = { params: Promise<{ repoId: string }> };

export async function GET(req: NextRequest, context: RouteContext) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { repoId } = await context.params;

    // Verify access
    const repo = await prisma.repository.findUnique({
      where: { id: repoId },
      select: { id: true, name: true, slug: true, ownerId: true },
    });
    if (!repo) {
      return NextResponse.json({ error: "Repository not found" }, { status: 404 });
    }

    const { searchParams } = new URL(req.url);
    const format = searchParams.get("format") || "csv";
    const dateFrom = searchParams.get("dateFrom");
    const dateTo = searchParams.get("dateTo");
    const action = searchParams.get("action");

    // Build query filter
    const where: Record<string, unknown> = { repoId };
    if (action) where.action = action;
    if (dateFrom || dateTo) {
      where.createdAt = {
        ...(dateFrom && { gte: new Date(dateFrom) }),
        ...(dateTo && { lte: new Date(dateTo) }),
      };
    }

    const logs = await prisma.auditLog.findMany({
      where,
      include: {
        user: { select: { name: true, email: true } },
      },
      orderBy: { createdAt: "desc" },
      take: 5000,
    });

    const now = new Date().toISOString().split("T")[0];

    if (format === "pdf") {
      const doc = new jsPDF();

      // Header
      doc.setFontSize(18);
      doc.setTextColor(22, 163, 74); // brand green
      doc.text("ExcelHub", 14, 20);
      doc.setFontSize(12);
      doc.setTextColor(55, 65, 81);
      doc.text(`Audit Log — ${repo.name}`, 14, 30);
      doc.setFontSize(9);
      doc.setTextColor(107, 114, 128);
      doc.text(`Generated: ${now}`, 14, 37);

      const filterParts: string[] = [];
      if (action) filterParts.push(`Action: ${action}`);
      if (dateFrom) filterParts.push(`From: ${dateFrom}`);
      if (dateTo) filterParts.push(`To: ${dateTo}`);
      if (filterParts.length > 0) {
        doc.text(`Filters: ${filterParts.join(" | ")}`, 14, 43);
      }

      // Table
      const tableData = logs.map((log) => [
        new Date(log.createdAt).toLocaleString("en-US", {
          dateStyle: "short",
          timeStyle: "short",
        }),
        log.action.replace(/_/g, " "),
        log.user?.name || log.user?.email || "System",
        formatMetadata(log.metadata as Record<string, unknown>),
      ]);

      autoTable(doc, {
        startY: filterParts.length > 0 ? 48 : 42,
        head: [["Date", "Action", "User", "Details"]],
        body: tableData,
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: {
          fillColor: [22, 163, 74],
          textColor: 255,
          fontStyle: "bold",
        },
        alternateRowStyles: { fillColor: [245, 247, 250] },
        columnStyles: {
          0: { cellWidth: 35 },
          1: { cellWidth: 35 },
          2: { cellWidth: 30 },
          3: { cellWidth: "auto" },
        },
      });

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(156, 163, 175);
        doc.text(
          `Page ${i} of ${pageCount} — Generated by ExcelHub`,
          14,
          doc.internal.pageSize.height - 10
        );
      }

      const pdfBuffer = doc.output("arraybuffer");
      return new NextResponse(pdfBuffer, {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="audit-log-${repo.slug}-${now}.pdf"`,
        },
      });
    }

    // CSV format
    const headers = ["Date", "Action", "User", "Email", "IP Address", "Details"];
    const rows = logs.map((log) => [
      new Date(log.createdAt).toISOString(),
      log.action,
      log.user?.name || "",
      log.user?.email || "",
      log.ipAddress || "",
      JSON.stringify(log.metadata),
    ]);

    const csv = [headers, ...rows]
      .map((row) =>
        row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")
      )
      .join("\n");

    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="audit-log-${repo.slug}-${now}.csv"`,
      },
    });
  } catch (error) {
    console.error("Error exporting audit logs:", error);
    return NextResponse.json(
      { error: "Failed to export audit logs" },
      { status: 500 }
    );
  }
}

function formatMetadata(metadata: Record<string, unknown>): string {
  const parts: string[] = [];
  for (const [key, value] of Object.entries(metadata)) {
    if (value !== null && value !== undefined) {
      parts.push(`${key}: ${String(value)}`);
    }
  }
  return parts.join(", ");
}
